### ISSUE TITLE
PHP 5.6.11_1 problem

### ISSUE THREAD

**Issue by it-can** [Homebrew/homebrew-php#1901]
Hi,

I updated my homebrew PHP56 package to 5.6.11_1 but now when I want to use something like composer or just PHP from the CLI, I get this error:

Mac OS X: 10.10.4

```
dyld: Library not loaded: /usr/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/Cellar/php56/5.6.11_1/bin/php
  Reason: image not found
```

**output of php -v**
```
php -v
dyld: Library not loaded: /usr/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by it-can** [comment]
Ok problem fixed... Had to link openssl

```
brew link openssl --force
```

**Comment by it-can** [comment]
I don't know if this is a "good" solution...

**Comment by DsXack** [comment]
thanks, this is solved fo me

**Comment by it-can** [comment]
Yeah, but homebrew warns that linking OpenSSL could give system problems for OS X... So...

**Comment by DomT4** [comment]
`brew reinstall php56` would be less risky here. We briefly made OpenSSL non-key-only in the core to solve some 10.11 issues, and then discovered Clang/LD linking defaults are fun (https://github.com/Homebrew/homebrew/issues/41613) and so we had to revert that. Anything built in the ~4 days before we reverted it needs to be rebuilt.

**Comment by pablocarreraest** [comment]
thanks the advice!

**Comment by jeffhertzler** [comment]
Clearing my cache and making sure homebrew was up-to-date plus reinstalling openssl & php56 did not fix the issue for me.

`brew link openssl --force` did work for now.

**Comment by DomT4** [comment]
Hmm. Give me a bit, I'll look into it.

**Comment by DomT4** [comment]
Yeah, the bottle is still linked to the unkegged OpenSSL.

```
dyld: Library not loaded: /usr/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/opt/php56/bin/php
  Reason: image not found
[1]    12887 trace trap  php
```

It'll need to be regenerated, CC @Homebrew/php. For now, you can work around it with `brew reinstall php56 -fs`.

**Comment by jeffhertzler** [comment]
Thanks! Unlinked SSL and reinstalled from source. Works great.

**Comment by ablyler** [comment]
@DomT4: okay, I'll bump the rev on the core php formulas.

**Comment by ablyler** [comment]
bottles recreated and revision bumped

**Comment by basemkhirat** [comment]
`brew reinstall openssl`
worked for me
