### ISSUE TITLE
revisions for icu4c 58.1 needed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-php#3752]
- [x] php53-intl
- [x] php54-intl
- [x] php55-intl
- [x] php56-intl
- [x] php70-intl
- [x] php71-intl
- [x] phpbrew

CC @javian

RE: https://github.com/Homebrew/homebrew-core/pull/6505

**Comment by craigcarnell** [comment]
```
php -v

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-intl/intl.so' - dlopen(/usr/local/opt/php70-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.57.dylib
  Referenced from: /usr/local/opt/php70-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP 7.0.12 (cli) (built: Oct 14 2016 09:56:59) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by pinepain** [comment]
PR #3760 submitted. PTAL.

**Comment by ilovezfs** [comment]
@craigcarnell well yes, that's why the revision bumps are needed.

**Comment by javian** [comment]
This should have been corrected now and new bottles are created.

**Comment by srl295** [comment]
I suspect the issue is the same as I hit for couchdb in https://gist.github.com/srl295/fe933c5e5ccb3a84ef2347f92a47a577#file-brew-relink-old-icus-md

**Comment by patrickomeara** [comment]
I'm having this issue with `php71-intl` and moving icu4c from 58 to 59. 

I've tried building php71-intl from source like @craigcarnell says, but get this error:

```
Last 15 lines from /Users/<user>/Library/Logs/Homebrew/php71-intl/03.make:
      UnicodeString(ConstChar16Ptr(text), length) {}
      ^~~~~~~~~~~~~
/usr/local/Cellar/icu4c/59.1/include/unicode/unistr.h:3180:7: error: delegating constructors are permitted only in C++11
      UnicodeString(Char16Ptr(buffer), buffLength, buffCapacity) {}
      ^~~~~~~~~~~~~
```

and @srl295's symlinking fix. Still getting this error which is missing the symbol:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): Symbol not found: __ZN6icu_5813BreakIterator16getRuleStatusVecEPiiR10UErrorCode
  Referenced from: /usr/local/opt/php71-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php71-intl/intl.so in Unknown on line 0
```

@DomT4 or @alanthing any ideas how to remedy this?

**Comment by LEI** [comment]
Tried with `php72`, I get a similar error:

```
$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-intl/intl.so' (tried: /usr/local/opt/php72-intl/intl.so (dlopen(/usr/local/opt/php72-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
  Referenced from: /usr/local/opt/php72-intl/intl.so
  Reason: image not found), /usr/local/Cellar/php72/7.2.0beta2_4/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-intl/intl.so.so (dlopen(/usr/local/Cellar/php72/7.2.0beta2_4/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-intl/intl.so.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php72-intl/intl.so' (tried: /usr/local/opt/php72-intl/intl.so (dlopen(/usr/local/opt/php72-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
  Referenced from: /usr/local/opt/php72-intl/intl.so
  Reason: image not found), /usr/local/Cellar/php72/7.2.0beta2_4/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-intl/intl.so.so (dlopen(/usr/local/Cellar/php72/7.2.0beta2_4/lib/php/extensions/no-debug-non-zts-20170718//usr/local/opt/php72-intl/intl.so.so, 9): image not found)) in Unknown on line 0
PHP 7.2.0beta2 (cli) (built: Aug  7 2017 16:06:18) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
```

Also when building `php72-intl` from source:

```
Last 15 lines from /Users/Guillaume/Library/Logs/Homebrew/php72-intl/03.make:
      UnicodeString(ConstChar16Ptr(text)) {}
      ^~~~~~~~~~~~~
/usr/local/Cellar/icu4c/59.1/include/unicode/unistr.h:3087:7: error: delegating constructors are permitted only in C++11
      UnicodeString(ConstChar16Ptr(text), length) {}
      ^~~~~~~~~~~~~
/usr/local/Cellar/icu4c/59.1/include/unicode/unistr.h:3180:7: error: delegating constructors are permitted only in C++11
      UnicodeString(Char16Ptr(buffer), buffLength, buffCapacity) {}
      ^~~~~~~~~~~~~
```

The only version installed is `/usr/local/Cellar/icu4c/59.1`, I guess the *58.1* is needed.

**Comment by jak** [comment]
workaround: `brew switch icu4c 58.2`

**Comment by LEI** [comment]
In this case only the 59.1 is present, my mistake was probably to execute `brew cleanup` after updating.

Is there a way to install the previous version?

```
$ brew switch icu4c 58.2
Error: icu4c does not have a version "58.2" in the Cellar.
Versions available: 59.1
```

Disabling the `php-intl` extension stops the warnings but it's only a temporary fix.

**Comment by jak** [comment]
There is an alternative in #4384 - that's also probably the best issue to watch

**Comment by Gounlaf** [comment]
@LEI 

Go to homebrew-core tap (default path below):
`cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core`

Checkout previous version of icu4c (version found in history; different way to do it):
`git checkout e1b518a22 Formula/icu4c.rb`

Then reinstall icu4c:
`brew reinstall icu4c`

**Comment by LEI** [comment]
Thanks @Gounlaf this may come in useful next time, but I was able to directly fix the formula with the issue referenced above:

- `brew edit php71-intl`
- Apply changes of the corresponding PHP version: https://github.com/Homebrew/homebrew-php/pull/4382/files (especially `ENV.cxx11`)
- `brew reinstall -s php71-intl`
